// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Test
{
	using global::Avro;
	using global::Avro.Specific;

	public partial class data : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""data"",""namespace"":""Test"",""fields"":[{""name"":""publishedTime"",""type"":""string""}]}");
		private string _publishedTime;
		public virtual Schema Schema
		{
			get
			{
				return data._SCHEMA;
			}
		}
		public string publishedTime
		{
			get
			{
				return this._publishedTime;
			}
			set
			{
				this._publishedTime = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.publishedTime;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.publishedTime = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
